# Generated by Django 3.0.3 on 2020-02-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title',
                 models.CharField(help_text='Titel der Ankündigung', max_length=256, verbose_name='Überschrift')),
                ('text', models.TextField(help_text='Erläuterung der Ankündigung', verbose_name='Ankündigungstext')),
                ('start', models.DateTimeField(help_text='Zeitpunkt ab dem die Ankündigung angezeigt werden soll',
                                               verbose_name='Startzeitpunkt')),
                ('end', models.DateTimeField(help_text='Zeitpunkt bis zu dem die Ankündigung angezeigt werden soll',
                                             verbose_name='Endzeitpunkt')),
            ],
            options={
                'verbose_name': 'Ankündigung',
                'verbose_name_plural': 'Ankündigungen',
            },
        ),
    ]
