# Generated by Django 4.1.2 on 2022-10-30 21:03

import dachor_website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dachor_website', '0001_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True, validators=[dachor_website.models.validate_birthday], verbose_name='Geburtstag'),
        ),
    ]
