# Generated by Django 4.1.2 on 2022-10-31 11:58

import dachor_internal.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations = [
                migrations.CreateModel(
                    name='Profile',
                    fields=[
                        ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                        ('birthday', models.DateField(blank=True, null=True, validators=[dachor_internal.models.validate_birthday], verbose_name='Geburtstag')),
                        ('Stimme', models.CharField(choices=[('S', 'Sopran'), ('A', 'Alt'), ('T', 'Tenor'), ('B', 'Bass')], max_length=1)),
                    ],
                    options={
                        'verbose_name': 'Profil',
                        'verbose_name_plural': 'Profile',
                    },
                ),
            ],
            # Table already exists, see dachor_website/migrations/0003_move_profile.py
            database_operations=[]
        )
    ]

